---
title: "HW 4"
author: "Licza Lobo"
date: "10/10/2024"
output:
  pdf_document: default
  html_document:
    number_sections: true
---

This homework is designed to give you practice working with statistical/philosophical measures of fairness. 

#
The paper linked below^[https://link.springer.com/article/10.1007/s00146-023-01676-3] discusses potential algorithmic bias in the context of credit.  In particular, banks are now regularly using machine learning algorithms to do an initial screening for credit-worthy loan applicants.  In section 4.5.2, this paper reports the rates at which various racial groups were granted a mortgage.  If we assume that it is a classifier making these predictions^[It is unclear whether this is an algorithm producing these predictions or human] what additional information would be necessary to assess this classifier according to equalized odds?

Equalized odds is a fairness criterion that measures True Positive Rates and False Positive Rates across different protected classes, such as race and sex. In section 4.5.2, the paper reports disparities in mortgage approval rates by race. To assess this classifier according to equalized odds, we would need a pre-defined error rate to compare each odds measure to. If either the TPR or FPR is unequal, the classifier violates equalized odds. It would also be necessary to have a measure of individuals' true credit standing. This can help us measure the proportion of individuals approved who should have been and those who were denied who should not have been, by race.

#
Show or argue that the impossibility result discussed in class does not hold when our two fringe cases^[a) perfect predicting classifier and b) perfectly equal proportions of ground truth class labels across the protected variable] are met.  

In the case of a perfect predicting classifier, the TPR are 100% across all groups. This means the classifier makes no errors, thereby satisfying the criteria for equalized odds. Since there are no misclassifications, the classifier achieves perfect fairness without any decrease in accuracy,  violating the impossibility result. In the second case, when the underlying base rates are equal across groups, the classifier can meet fairness criteria inherently. With balanced class distributions, the model can achieve both accuracy and fairness simultaneously, as the predicted proportions align with the true proportions of outcomes. Therefore, the impossibility result does not hold either.

#

How would Rawls's Veil of Ignorance define a protected class?  Further, imagine that we preprocessed data by removing this protected variable from consideration before training out algorithm.  How could this variable make its way into our interpretation of results nonetheless?

Rawls's Veil of Ignorance defines a protected class without individuals knowing which group they belong to themselves. This allows for protections to be assigned without bias, focusing on groups likely to face discrimination. However, omitted protected variables may still influence the interpretation of results if they are confounded with other variables. These correlated variables can serve as proxies for the protected class if they are also discriminated against by that class. For example, zip codes may correlate with high concentrations of minority populations.

#

Based on all arguments discussed in class, is the use of COMPAS to supplement a judge's discretion justifiable.  Defend your position.  This defense should appeal to statistical and philosophical measures of fairness as well as one of our original moral frameworks from the beginning of the course.  Your response should be no more than a paragraph in length. 

No, the use of COMPAS to supplement a judge's discretion is not justifiable. Statistically, the algorithm violates the criteria for equalized odds, as it has different TPR by race, resulting in disparate impact for minority individuals. Not only are minority individuals more likely to suffer from its use, but the algorithm is also only about 65% accurate, which is too low in the context of deciding whether an individual goes to jail. Considering the moral framework of Deontology, judges undergo training and take an oath to work without bias. By using a knowingly biased algorithm, they are failing to uphold their moral duty and obligations as judges. This contradicts the principles of Deontology, where moral actions are defined by duty, obligation, and intentions.
